# Generated by Django 3.0.4 on 2020-04-04 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='main.jpg', upload_to='profile_pics'),
        ),
    ]
