# Generated by Django 2.2.3 on 2019-07-26 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ViewATMStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('s_n', models.IntegerField()),
                ('branch_name',models.CharField()),
                ('problem', models.CharField(max_length=2083)),
                ('remarks', models.CharField(max_length=100)),
                ('terminal_id', models.CharField(max_length=17)),
                ('atm_terminal_name', models.CharField(max_length=25)),
                ('atm_ip_address', models.CharField(max_length=50)),
                ('switch_ip_address', models.CharField(max_length=50)),
                ('port_number', models.IntegerField()),
            ],
        ),
    ]
