# Generated by Django 2.2.3 on 2020-03-19 15:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ATMStatus', '0002_auto_20200319_2109'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atmdetails',
            name='branch_code',
            field=models.IntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='atmissuedetails',
            name='branch_code',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='AtmDetails_branch_code', to='ATMStatus.AtmDetails', to_field='branch_code'),
        ),
    ]
