# Generated by Django 2.2.3 on 2020-03-22 02:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ATMStatus', '0003_auto_20200319_2118'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='atmissuedetails',
            name='branch_name',
        ),
        migrations.AlterField(
            model_name='atmissuedetails',
            name='branch_code',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='AtmDetails_branch_code', to='ATMStatus.AtmDetails'),
        ),
    ]
