# Generated by Django 2.2.3 on 2019-08-06 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ATMStatus', '0003_auto_20190806_0731'),
    ]

    operations = [
        migrations.AlterField(
            model_name='viewatmstatus',
            name='atm_ip_address',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='viewatmstatus',
            name='atm_terminal_name',
            field=models.CharField(max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='viewatmstatus',
            name='branch_name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='viewatmstatus',
            name='port_number',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='viewatmstatus',
            name='problem',
            field=models.CharField(max_length=2083, null=True),
        ),
        migrations.AlterField(
            model_name='viewatmstatus',
            name='remarks',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='viewatmstatus',
            name='switch_ip_address',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='viewatmstatus',
            name='terminal_id',
            field=models.CharField(max_length=17, null=True),
        ),
    ]
