# Generated by Django 3.0.4 on 2020-04-17 04:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ATMStatus', '0004_auto_20200322_0746'),
    ]

    operations = [
        migrations.AddField(
            model_name='atmissuedetails',
            name='branch_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='AtmDetails_branch_name', to='ATMStatus.AtmDetails'),
        ),
        migrations.AlterField(
            model_name='atmdetails',
            name='branch_name',
            field=models.CharField(error_messages={'unique': 'Please provide valid Branch name.'}, max_length=100),
        ),
    ]
