# Generated by Django 3.0.4 on 2020-04-28 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ATMStatus', '0005_auto_20200417_1028'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='atmissuedetails',
            name='branch_name',
        ),
        migrations.AlterField(
            model_name='atmdetails',
            name='branch_name',
            field=models.CharField(max_length=100),
        ),
    ]
