# Generated by Django 3.0.4 on 2020-04-29 04:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ATMStatus', '0007_branchdetails'),
    ]

    operations = [
        migrations.AddField(
            model_name='atmissuedetails',
            name='branch_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='AtmDetails_branch_name', to='ATMStatus.AtmDetails'),
        ),
        migrations.AlterField(
            model_name='atmissuedetails',
            name='branch_code',
            field=models.IntegerField(null=True),
        ),
    ]
