# Generated by Django 3.0.4 on 2020-04-29 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ATMStatus', '0009_auto_20200429_1024'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atmdetails',
            name='branch_name',
            field=models.CharField(max_length=100),
        ),
    ]
