# Generated by Django 3.0.4 on 2020-04-29 05:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ATMStatus', '0010_auto_20200429_1038'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atmdetails',
            name='branch_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ATMStatus.BranchDetails'),
        ),
    ]
