# Generated by Django 3.0.4 on 2020-04-29 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ATMStatus', '0011_auto_20200429_1045'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atmdetails',
            name='branch_code',
            field=models.IntegerField(default='Please choose branch code'),
        ),
    ]
