# Generated by Django 3.0.4 on 2020-04-30 04:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ATMStatus', '0012_auto_20200429_1056'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atmdetails',
            name='branch_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='AtmDetails_branch_name', to='ATMStatus.BranchDetails'),
        ),
        migrations.AlterField(
            model_name='atmissuedetails',
            name='branch_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='AtmIssuedDetails_branch_name', to='ATMStatus.BranchDetails'),
        ),
        migrations.CreateModel(
            name='ATMLoginCredentialsDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('s_n', models.IntegerField()),
                ('branch_code', models.IntegerField()),
                ('ATM_IP', models.CharField(max_length=50)),
                ('VNC_password', models.CharField(max_length=50)),
                ('R_admin_user_name', models.CharField(max_length=50)),
                ('R_admin_password', models.CharField(max_length=50)),
                ('ATM_journal_user_name', models.CharField(max_length=50)),
                ('ATM_journal_password', models.CharField(max_length=50)),
                ('branch_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='BranchDetails_branch_name', to='ATMStatus.BranchDetails')),
            ],
        ),
    ]
