# Generated by Django 3.0.4 on 2020-06-04 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ATMStatus', '0016_auto_20200603_2106'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atmlogincredentialsdetails',
            name='VNC_password',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
