# Generated by Django 3.0.4 on 2020-06-04 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ATMStatus', '0019_auto_20200604_1449'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atmlogincredentialsdetails',
            name='R_admin_user_name',
            field=models.CharField(blank=True, default=' ', max_length=50, null=True),
        ),
    ]
